name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 20 * * *"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Test on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deploy CLI
        uses: ./
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test
        run: |
          rsync --version
          ssh -V
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "date"
